# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Docker space
        run: docker image prune -f

      - name: Build images
        run: |
          docker compose build db
          docker compose build api
          docker compose build web
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Stop old containers
        run: docker compose down

      - name: Start new containers
        run: |
          docker compose up -d